use_frameworks!

target 'NoCapture_Example' do
    pod 'NoCapture', :path => '../'

  target 'NoCapture_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
